name: '1.0$(rev:.r)'

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  Blackduck_Project: IT-Allegion-NA-SW-FO-ProductTech-BDLicense-Build
  Blackduck_Version: master-CIBuild
  Blackduck_LicenseFile: Black_Duck_Notices_Report.txt
  Blackduck_NoticeFileName: ${{ replace(format('{0}_{1}_{2}', variables.Blackduck_Project, variables.Blackduck_Version, variables.Blackduck_LicenseFile), '-', '_') }}

stages:
- stage: build
  jobs:
  - job: buildjob
    steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: $(System.DefaultWorkingDirectory)/licensegenerator/.npmrc

    - task: npmAuthenticate@0
      inputs:
        workingFile: $(System.DefaultWorkingDirectory)/.npmrc

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Use Node 20'

    - task: TfxInstaller@3
      inputs:
        version: "v0.11.x"

    - script: cd licensegenerator && npm install
      displayName: 'Install Packages'

    - task: Npm@1
      displayName: 'Build Package'
      inputs:
        command: custom
        customCommand: 'run build'

    - task: BlackDuckDetectTask@10
      displayName: 'BlackDuck Scan'
      inputs:
        BlackDuckScaService: black-duck-service-connection
        DetectArguments: |
          --detect.project.name="$(Blackduck_Project)"
          --detect.project.version.name="$(Blackduck_Version)"
          --detect.parallel.processors=-1
          --logging.level.com.synopsys.integration=INFO
          --detect.bom.aggregate.name="$(Blackduck_Project)-$(Blackduck_Version)-BOM"
          --detect.code.location.name="$(Blackduck_Project)-$(Blackduck_Version)-Scan"
          --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING
          --detect.wait.for.results=true
          --detect.scan.output.path=$(Agent.TempDirectory)/bdscan-$(Build.SourceVersion)
          --detect.bdio.output.path=$(Agent.TempDirectory)/bdbdio-$(Build.SourceVersion)
          --detect.npm.include.dev.dependencies=true
          --detect.source.path="$(System.DefaultWorkingDirectory)/licensegenerator"
          --detect.notices.report=true
          --detect.notices.report.path="$(System.DefaultWorkingDirectory)"
      continueOnError: true
    
    # - task: PublishPipelineArtifact@1
    #   displayName: 'Publish Pipeline Artifact: LicenseFile'
    #   inputs:
    #     targetPath: '$(System.DefaultWorkingDirectory)/$(Blackduck_NoticeFileName)'
    #     artifact: licensefile
    
    # - task: noticegenerator@0
    #   inputs:
    #     blackduckconnection: blackduck-service-token
    #     projectName: $(Blackduck_Project)
    #     versionName: $(Blackduck_Version)
    #     noticeFilePath: '$(System.DefaultWorkingDirectory)/third-party-licenses.txt'
    #     generateNoticeFile: true
    #     getLatestNoticeFile: true

    - task: PackageAzureDevOpsExtension@5
      displayName: 'Package Extension: Notice Generator'
      name: 'packageStep'
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)/blackducklicensegenerator.vsix'
        publisherId: 'ProductTech'
        extensionId: 'alle-bd-notices-extension'
        extensionTag: '-build'
        extensionName: 'Black Duck OSS Notice Generator'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: true
        updateTasksVersionType: patch
        extensionVisibility: private

    - publish: '$(Build.ArtifactStagingDirectory)/blackducklicensegenerator.vsix'
      artifact: task
      displayName: 'Publish Task'

- stage: dev
  dependsOn: build
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
  jobs:
  - deployment: devdeploymentjob
    environment: Task-Dev
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: task

            - task: TfxInstaller@3
              inputs:
                version: "v0.11.x"

# details on v5 task
# https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/PublishExtension/v5/task.json

            - task: PublishAzureDevOpsExtension@5 
              inputs:
                connectTo: 'VsTeam'
                connectedServiceName: 'ado-extension-connection'
                fileType: 'vsix'
                vsixFile: '$(Pipeline.Workspace)/task/blackducklicensegenerator.vsix'
                publisherId: 'ProductTech'
                extensionId: 'alle-bd-license-generator-test'
                extensionName: 'Black Duck License Generator Test'
                updateTasksId: true
                updateTasksVersion: false
                extensionVisibility: 'private'
                extensionPricing: 'free'
                extensionTag: '-test'

- stage: prod
  dependsOn: build
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual'))
  jobs:
  - deployment: proddeploymentjob
    environment: Task-Marketplace
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: task

            - task: TfxInstaller@3
              inputs:
                version: "v0.11.x"

            - task: PublishAzureDevOpsExtension@3
              inputs:
                connectTo: 'VsTeam'
                connectedServiceName: 'ado-extension-connection'
                fileType: 'vsix'
                vsixFile: '$(Pipeline.Workspace)/task/blackducklicensegenerator.vsix'
                publisherId: 'ProductTech'
                extensionId: 'alle-bd-license-generator'
                extensionName: 'Black Duck License Generator'
                updateTasksVersion: false
                extensionVisibility: 'private'
                extensionPricing: 'free'